### ISSUE TITLE
Can we have access to code?

### ISSUE THREAD

**Issue by ffabreti** [dchacke/entangled-angular#2]
I mean, not minimized.

**Comment by dchacke** [comment]
It's in the dummy app in the main repo's specs: https://github.com/dchacke/entangled/blob/development/spec/dummy/public/app/entangled/entangled.js

The minified code is just for distribution as a Bower package.

If you want to contribute, check the contribution guide in the main repo: https://github.com/dchacke/entangled#contributing

**Comment by ffabreti** [comment]
Great, Thanks. I intend to contribute, the whole entangled project is a jewel!
